version: '3.9'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
      - REACT_APP_FRONTEND_URL=http://localhost:3000
    networks:
      - training_app

  backend:
    build: 
      context: ./backend
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www/laravel
    environment:
      - BACKEND_APP_URL=http://localhost:8000
      - FRONTEND_APP_URL=http://localhost:3000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=sph_els_stephen
      - DB_USERNAME=training_app
      - DB_PASSWORD=training_app
      - FILESYSTEM_DRIVER=public
      - SESSION_DOMAIN=localhost
    networks:
      - training_app
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: training_app
      MYSQL_PASSWORD: training_app
      MYSQL_DATABASE: sph_els_stephen
    networks:
      - training_app
    ports:
      - 3306:3306
    volumes:
      - training_db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - training_app

networks:
  training_app:
    driver: bridge


volumes:
  training_db:
    driver: local